# Generated by Django 4.1 on 2023-07-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='media/')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
